name: Publish to Registry

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ffmpeg
      run: sudo add-apt-repository ppa:jonathonf/ffmpeg-4 && sudo apt-get update && sudo apt-get install ffmpeg
    - name: Install dependencies
      run: yarn install
    - name: Create .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=$PUBLISH_TOKEN" >> ~/.npmrc
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    - name: Publish
      run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
